import type { Contact } from '@/types/contact';

export const mockContacts: Contact[] = [
  {
    id: '1',
    firstname: 'John',
    lastname: 'Doe',
    email: 'john.doe@example.com',
    phone: '123-456-7890',
    company: 'Acme Corp',
    status: 'active',
    type: 'customer',
    title: 'Software Engineer',
    department: 'Engineering',
    timezone: 'America/Los_Angeles',
    linkedinUrl: 'linkedin.com/in/johndoe',
    twitterUrl: 'twitter.com/johndoe',
    language: 'en',
    source: 'website',
    assignedTo: 'user123',
    accountValue: 5000,
    tags: [
      { id: "tag1", name: "VIP" },
      { id: "tag2", name: "New" },
      { id: "tag3", name: "Enterprise" }
    ],
    notes: 'High potential customer',
    lastContacted: '2024-03-10',
    createdAt: '2024-01-15',
    updatedAt: '2024-03-10',
    street: '123 Main St',
    city: 'Los Angeles',
    state: 'CA',
    postalCode: '90001',
    country: 'USA',
  },
  {
    id: '2',
    firstname: 'Jane',
    lastname: 'Smith',
    email: 'jane.smith@example.com',
    phone: '987-654-3210',
    company: 'Beta Inc',
    status: 'active',
    type: 'customer',
    title: 'Marketing Manager',
    department: 'Marketing',
    timezone: 'Europe/London',
    linkedinUrl: 'linkedin.com/in/janesmith',
    twitterUrl: 'twitter.com/janesmith',
    language: 'en',
    source: 'referral',
    assignedTo: 'user456',
    accountValue: 3000,
    tags: [
      { id: "tag1", name: "VIP" },
      { id: "tag2", name: "New" }
    ],
    notes: 'Interested in new products',
    lastContacted: '2024-03-05',
    createdAt: '2024-02-01',
    updatedAt: '2024-03-05',
    street: '456 Elm St',
    city: 'London',
    state: null,
    postalCode: 'SW1A 0AA',
    country: 'UK',
  },
  {
    id: '3',
    firstname: 'Alice',
    lastname: 'Johnson',
    email: 'alice.johnson@example.com',
    phone: '555-123-4567',
    company: 'Gamma Ltd',
    status: 'inactive',
    type: 'customer',
    title: 'Sales Representative',
    department: 'Sales',
    timezone: 'Asia/Tokyo',
    linkedinUrl: 'linkedin.com/in/alicejohnson',
    twitterUrl: 'twitter.com/alicejohnson',
    language: 'ja',
    source: 'marketing',
    assignedTo: 'user789',
    accountValue: 2000,
    tags: [
      { id: "tag1", name: "VIP" },
      { id: "tag2", name: "New" }
    ],
    notes: 'Needs follow-up',
    lastContacted: '2024-02-20',
    createdAt: '2023-11-01',
    updatedAt: '2024-02-20',
    street: '789 Oak St',
    city: 'Tokyo',
    state: null,
    postalCode: '100-0001',
    country: 'Japan',
  },
  {
    id: '4',
    firstname: 'Bob',
    lastname: 'Williams',
    email: 'bob.williams@example.com',
    phone: '111-222-3333',
    company: 'Delta Co',
    status: 'active',
    type: 'customer',
    title: 'Customer Support',
    department: 'Support',
    timezone: 'Australia/Sydney',
    linkedinUrl: 'linkedin.com/in/bobwilliams',
    twitterUrl: 'twitter.com/bobwilliams',
    language: 'en',
    source: 'website',
    assignedTo: 'user101',
    accountValue: 4000,
    tags: [
      { id: "tag1", name: "VIP" },
      { id: "tag2", name: "New" },
      { id: "tag3", name: "Enterprise" }
    ],
    notes: 'Satisfied customer',
    lastContacted: '2024-03-01',
    createdAt: '2023-12-15',
    updatedAt: '2024-03-01',
    street: '101 Pine St',
    city: 'Sydney',
    state: null,
    postalCode: '2000',
    country: 'Australia',
  },
  {
    id: '5',
    firstname: 'Eve',
    lastname: 'Brown',
    email: 'eve.brown@example.com',
    phone: '444-555-6666',
    company: 'Epsilon LLC',
    status: 'active',
    type: 'customer',
    title: 'Product Manager',
    department: 'Product',
    timezone: 'Europe/Berlin',
    linkedinUrl: 'linkedin.com/in/evebrown',
    twitterUrl: 'twitter.com/evebrown',
    language: 'de',
    source: 'referral',
    assignedTo: 'user202',
    accountValue: 2500,
    tags: [
      { id: "tag1", name: "VIP" },
      { id: "tag2", name: "New" }
    ],
    notes: 'Potential upsell opportunity',
    lastContacted: '2024-02-25',
    createdAt: '2024-01-01',
    updatedAt: '2024-02-25',
    street: '222 Cedar St',
    city: 'Berlin',
    state: null,
    postalCode: '10115',
    country: 'Germany',
  }
];
