
import { Contact } from '@/types/contact';

export const mockContacts: Contact[] = [
  {
    id: '1',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@techinnovators.com',
    phone: '+1 (555) 111-2233',
    company: 'Tech Innovators Inc.',
    status: 'active',
    type: 'customer',
    title: 'Chief Technology Officer',
    department: 'Technology',
    timezone: 'America/Los_Angeles',
    linkedinUrl: 'https://linkedin.com/in/sarahjohnson',
    twitterUrl: 'https://twitter.com/sarahjtech',
    preferredLanguage: 'English',
    source: 'website',
    assignedTo: 'John Smith',
    accountValue: 250000,
    tags: ['vip', 'enterprise', 'tech'],
    notes: 'Key decision maker for enterprise solutions',
    lastContacted: new Date(2024, 2, 10).toISOString(),
    createdAt: new Date(2024, 0, 15).toISOString(),
    updatedAt: new Date(2024, 2, 15).toISOString(),
    street: '789 Innovation Drive',
    city: 'San Francisco',
    state: 'CA',
    postalCode: '94105',
    country: 'USA'
  },
  {
    id: '2',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'michael.chen@globalsolutions.com',
    phone: '+1 (555) 444-5555',
    company: 'Global Solutions Corp',
    status: 'active',
    type: 'customer',
    title: 'VP of Operations',
    department: 'Operations',
    timezone: 'America/New_York',
    linkedinUrl: 'https://linkedin.com/in/michaelchen',
    preferredLanguage: 'English',
    source: 'referral',
    assignedTo: 'Emma Wilson',
    accountValue: 150000,
    tags: ['partner', 'operations'],
    notes: 'Interested in expanding partnership',
    lastContacted: new Date(2024, 2, 8).toISOString(),
    createdAt: new Date(2024, 1, 1).toISOString(),
    updatedAt: new Date(2024, 2, 10).toISOString(),
    street: '456 Business Avenue',
    city: 'New York',
    state: 'NY',
    postalCode: '10013',
    country: 'USA'
  },
  {
    id: '3',
    firstName: 'Emma',
    lastName: 'Rodriguez',
    email: 'emma.rodriguez@ecotechventures.com',
    phone: '+1 (555) 777-8888',
    company: 'EcoTech Ventures',
    status: 'active',
    type: 'prospect',
    title: 'Sustainability Director',
    department: 'Environmental',
    timezone: 'America/Chicago',
    linkedinUrl: 'https://linkedin.com/in/emmarodriguez',
    preferredLanguage: 'English',
    source: 'marketing',
    assignedTo: 'David Brown',
    accountValue: 100000,
    tags: ['green-tech', 'prospect'],
    notes: 'Looking for sustainable technology solutions',
    lastContacted: new Date(2024, 2, 5).toISOString(),
    createdAt: new Date(2024, 1, 15).toISOString(),
    updatedAt: new Date(2024, 2, 5).toISOString(),
    street: '123 Green Street',
    city: 'Austin',
    state: 'TX',
    postalCode: '78701',
    country: 'USA'
  },
  {
    id: '4',
    firstName: 'David',
    lastName: 'Kim',
    email: 'david.kim@digitaldynamics.tech',
    phone: '+1 (555) 999-0000',
    company: 'Digital Dynamics Ltd',
    status: 'active',
    type: 'customer',
    title: 'Marketing Director',
    department: 'Marketing',
    timezone: 'America/Los_Angeles',
    linkedinUrl: 'https://linkedin.com/in/davidkim',
    twitterUrl: 'https://twitter.com/davidkimdigital',
    preferredLanguage: 'English',
    source: 'website',
    assignedTo: 'Sarah Parker',
    accountValue: 75000,
    tags: ['digital-marketing', 'smb'],
    notes: 'Interested in digital transformation services',
    lastContacted: new Date(2024, 2, 12).toISOString(),
    createdAt: new Date(2024, 2, 1).toISOString(),
    updatedAt: new Date(2024, 2, 15).toISOString(),
    street: '321 Digital Lane',
    city: 'Seattle',
    state: 'WA',
    postalCode: '98101',
    country: 'USA'
  },
  {
    id: '5',
    firstName: 'Jennifer',
    lastName: 'Lee',
    email: 'jennifer.lee@healthtechsolutions.com',
    phone: '+1 (555) 222-3333',
    company: 'HealthTech Solutions',
    status: 'active',
    type: 'customer',
    title: 'Healthcare Solutions Architect',
    department: 'Technology',
    timezone: 'America/New_York',
    linkedinUrl: 'https://linkedin.com/in/jenniferlee',
    preferredLanguage: 'English',
    source: 'sales',
    assignedTo: 'Michael Thompson',
    accountValue: 200000,
    tags: ['healthcare', 'enterprise'],
    notes: 'Leading healthcare technology implementation',
    lastContacted: new Date(2024, 2, 14).toISOString(),
    createdAt: new Date(2024, 2, 15).toISOString(),
    updatedAt: new Date(2024, 2, 15).toISOString(),
    street: '567 Medical Drive',
    city: 'Boston',
    state: 'MA',
    postalCode: '02110',
    country: 'USA'
  }
];
