// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiovtfvunrdrfthcxiov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpb3Z0ZnZ1bnJkcmZ0aGN4aW92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMjA3MDgsImV4cCI6MjA1NDY5NjcwOH0.5Hamz3sr6yYHd6vOtWaeWZMuk9QdNHPBxCt2kbCy93o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);